2016-03-28 11:40:36,702 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-613
2016-03-28 11:40:42,044 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:40:42,046 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18108:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53729, localBroker= vm://Broker-three#18104
2016-03-28 11:40:42,046 | INFO  | Network connection between vm://Broker-three#18104 and tcp://localhost/127.0.0.1:61618@53729 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53729, localBroker= vm://Broker-three#18104
2016-03-28 11:40:42,048 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-605
2016-03-28 11:40:47,085 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:40:47,089 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18110:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53731, localBroker= vm://Broker-three#18106
2016-03-28 11:40:47,089 | INFO  | Network connection between vm://Broker-three#18106 and tcp://localhost/127.0.0.1:61618@53731 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53731, localBroker= vm://Broker-three#18106
2016-03-28 11:40:47,091 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-613
2016-03-28 11:40:52,133 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:40:52,135 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18112:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53746, localBroker= vm://Broker-three#18108
2016-03-28 11:40:52,135 | INFO  | Network connection between vm://Broker-three#18108 and tcp://localhost/127.0.0.1:61618@53746 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53746, localBroker= vm://Broker-three#18108
2016-03-28 11:40:52,137 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-612
2016-03-28 11:40:57,175 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:40:57,178 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18114:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53750, localBroker= vm://Broker-three#18110
2016-03-28 11:40:57,178 | INFO  | Network connection between vm://Broker-three#18110 and tcp://localhost/127.0.0.1:61618@53750 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53750, localBroker= vm://Broker-three#18110
2016-03-28 11:40:57,180 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-605
2016-03-28 11:41:02,222 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:41:02,231 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18116:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53753, localBroker= vm://Broker-three#18112
2016-03-28 11:41:02,231 | INFO  | Network connection between vm://Broker-three#18112 and tcp://localhost/127.0.0.1:61618@53753 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53753, localBroker= vm://Broker-three#18112
2016-03-28 11:41:02,233 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-613
2016-03-28 11:41:07,268 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:41:07,270 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18118:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53755, localBroker= vm://Broker-three#18114
2016-03-28 11:41:07,270 | INFO  | Network connection between vm://Broker-three#18114 and tcp://localhost/127.0.0.1:61618@53755 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53755, localBroker= vm://Broker-three#18114
2016-03-28 11:41:07,272 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-612
2016-03-28 11:41:12,310 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:41:12,313 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18120:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53757, localBroker= vm://Broker-three#18116
2016-03-28 11:41:12,313 | INFO  | Network connection between vm://Broker-three#18116 and tcp://localhost/127.0.0.1:61618@53757 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53757, localBroker= vm://Broker-three#18116
2016-03-28 11:41:12,315 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-605
2016-03-28 11:41:17,354 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:41:17,357 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18122:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53759, localBroker= vm://Broker-three#18118
2016-03-28 11:41:17,357 | INFO  | Network connection between vm://Broker-three#18118 and tcp://localhost/127.0.0.1:61618@53759 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53759, localBroker= vm://Broker-three#18118
2016-03-28 11:41:17,358 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-612
2016-03-28 11:41:22,399 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:41:22,402 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18124:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53762, localBroker= vm://Broker-three#18120
2016-03-28 11:41:22,402 | INFO  | Network connection between vm://Broker-three#18120 and tcp://localhost/127.0.0.1:61618@53762 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53762, localBroker= vm://Broker-three#18120
2016-03-28 11:41:22,405 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-613
2016-03-28 11:41:27,444 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:41:27,447 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18126:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53764, localBroker= vm://Broker-three#18122
2016-03-28 11:41:27,447 | INFO  | Network connection between vm://Broker-three#18122 and tcp://localhost/127.0.0.1:61618@53764 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53764, localBroker= vm://Broker-three#18122
2016-03-28 11:41:27,449 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-613
2016-03-28 11:41:32,494 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:41:32,498 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18128:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53767, localBroker= vm://Broker-three#18124
2016-03-28 11:41:32,498 | INFO  | Network connection between vm://Broker-three#18124 and tcp://localhost/127.0.0.1:61618@53767 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53767, localBroker= vm://Broker-three#18124
2016-03-28 11:41:32,500 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-612
2016-03-28 11:41:37,540 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:41:37,542 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18130:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53769, localBroker= vm://Broker-three#18126
2016-03-28 11:41:37,542 | INFO  | Network connection between vm://Broker-three#18126 and tcp://localhost/127.0.0.1:61618@53769 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53769, localBroker= vm://Broker-three#18126
2016-03-28 11:41:37,544 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-605
2016-03-28 11:41:42,583 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:41:42,585 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18132:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53771, localBroker= vm://Broker-three#18128
2016-03-28 11:41:42,585 | INFO  | Network connection between vm://Broker-three#18128 and tcp://localhost/127.0.0.1:61618@53771 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53771, localBroker= vm://Broker-three#18128
2016-03-28 11:41:42,587 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-613
2016-03-28 11:41:47,630 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:41:47,633 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18134:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53773, localBroker= vm://Broker-three#18130
2016-03-28 11:41:47,633 | INFO  | Network connection between vm://Broker-three#18130 and tcp://localhost/127.0.0.1:61618@53773 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53773, localBroker= vm://Broker-three#18130
2016-03-28 11:41:47,634 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-612
2016-03-28 11:41:52,668 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:41:52,672 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18136:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53775, localBroker= vm://Broker-three#18132
2016-03-28 11:41:52,672 | INFO  | Network connection between vm://Broker-three#18132 and tcp://localhost/127.0.0.1:61618@53775 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53775, localBroker= vm://Broker-three#18132
2016-03-28 11:41:52,675 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-605
2016-03-28 11:41:57,712 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:41:57,714 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18138:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53777, localBroker= vm://Broker-three#18134
2016-03-28 11:41:57,715 | INFO  | Network connection between vm://Broker-three#18134 and tcp://localhost/127.0.0.1:61618@53777 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53777, localBroker= vm://Broker-three#18134
2016-03-28 11:41:57,717 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-605
2016-03-28 11:42:02,757 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:42:02,760 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18140:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53780, localBroker= vm://Broker-three#18136
2016-03-28 11:42:02,760 | INFO  | Network connection between vm://Broker-three#18136 and tcp://localhost/127.0.0.1:61618@53780 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53780, localBroker= vm://Broker-three#18136
2016-03-28 11:42:02,762 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-612
2016-03-28 11:42:07,801 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:42:07,805 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18142:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53782, localBroker= vm://Broker-three#18138
2016-03-28 11:42:07,805 | INFO  | Network connection between vm://Broker-three#18138 and tcp://localhost/127.0.0.1:61618@53782 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53782, localBroker= vm://Broker-three#18138
2016-03-28 11:42:07,807 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-612
2016-03-28 11:42:12,844 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:42:12,847 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18144:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53784, localBroker= vm://Broker-three#18140
2016-03-28 11:42:12,847 | INFO  | Network connection between vm://Broker-three#18140 and tcp://localhost/127.0.0.1:61618@53784 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53784, localBroker= vm://Broker-three#18140
2016-03-28 11:42:12,848 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-605
2016-03-28 11:42:17,888 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:42:17,891 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18146:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53793, localBroker= vm://Broker-three#18142
2016-03-28 11:42:17,891 | INFO  | Network connection between vm://Broker-three#18142 and tcp://localhost/127.0.0.1:61618@53793 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53793, localBroker= vm://Broker-three#18142
2016-03-28 11:42:17,893 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-613
2016-03-28 11:42:22,932 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:42:22,934 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18148:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53795, localBroker= vm://Broker-three#18144
2016-03-28 11:42:22,934 | INFO  | Network connection between vm://Broker-three#18144 and tcp://localhost/127.0.0.1:61618@53795 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53795, localBroker= vm://Broker-three#18144
2016-03-28 11:42:22,936 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-612
2016-03-28 11:42:27,981 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:42:27,983 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18150:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53797, localBroker= vm://Broker-three#18146
2016-03-28 11:42:27,983 | INFO  | Network connection between vm://Broker-three#18146 and tcp://localhost/127.0.0.1:61618@53797 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53797, localBroker= vm://Broker-three#18146
2016-03-28 11:42:27,984 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-613
2016-03-28 11:42:33,023 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:42:33,029 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18152:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53809, localBroker= vm://Broker-three#18148
2016-03-28 11:42:33,029 | INFO  | Network connection between vm://Broker-three#18148 and tcp://localhost/127.0.0.1:61618@53809 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53809, localBroker= vm://Broker-three#18148
2016-03-28 11:42:33,031 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-612
2016-03-28 11:42:38,065 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:42:38,067 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18154:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53815, localBroker= vm://Broker-three#18150
2016-03-28 11:42:38,068 | INFO  | Network connection between vm://Broker-three#18150 and tcp://localhost/127.0.0.1:61618@53815 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53815, localBroker= vm://Broker-three#18150
2016-03-28 11:42:38,069 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-605
2016-03-28 11:42:43,110 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:42:43,114 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18156:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53830, localBroker= vm://Broker-three#18152
2016-03-28 11:42:43,114 | INFO  | Network connection between vm://Broker-three#18152 and tcp://localhost/127.0.0.1:61618@53830 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53830, localBroker= vm://Broker-three#18152
2016-03-28 11:42:43,115 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-613
2016-03-28 11:42:48,155 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:42:48,158 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18158:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53833, localBroker= vm://Broker-three#18154
2016-03-28 11:42:48,158 | INFO  | Network connection between vm://Broker-three#18154 and tcp://localhost/127.0.0.1:61618@53833 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53833, localBroker= vm://Broker-three#18154
2016-03-28 11:42:48,160 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-605
2016-03-28 11:42:53,195 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:42:53,198 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18160:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53835, localBroker= vm://Broker-three#18156
2016-03-28 11:42:53,198 | INFO  | Network connection between vm://Broker-three#18156 and tcp://localhost/127.0.0.1:61618@53835 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53835, localBroker= vm://Broker-three#18156
2016-03-28 11:42:53,200 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-612
2016-03-28 11:42:58,241 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:42:58,245 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18162:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53837, localBroker= vm://Broker-three#18158
2016-03-28 11:42:58,245 | INFO  | Network connection between vm://Broker-three#18158 and tcp://localhost/127.0.0.1:61618@53837 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53837, localBroker= vm://Broker-three#18158
2016-03-28 11:42:58,247 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-612
2016-03-28 11:43:03,281 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:43:03,286 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18164:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53859, localBroker= vm://Broker-three#18160
2016-03-28 11:43:03,286 | INFO  | Network connection between vm://Broker-three#18160 and tcp://localhost/127.0.0.1:61618@53859 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53859, localBroker= vm://Broker-three#18160
2016-03-28 11:43:03,288 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-605
2016-03-28 11:43:08,326 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:43:08,331 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18166:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53868, localBroker= vm://Broker-three#18162
2016-03-28 11:43:08,331 | INFO  | Network connection between vm://Broker-three#18162 and tcp://localhost/127.0.0.1:61618@53868 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53868, localBroker= vm://Broker-three#18162
2016-03-28 11:43:08,333 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-605
2016-03-28 11:43:13,370 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:43:13,372 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18168:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53870, localBroker= vm://Broker-three#18164
2016-03-28 11:43:13,372 | INFO  | Network connection between vm://Broker-three#18164 and tcp://localhost/127.0.0.1:61618@53870 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53870, localBroker= vm://Broker-three#18164
2016-03-28 11:43:13,374 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-612
2016-03-28 11:43:18,411 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:43:18,414 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18170:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53872, localBroker= vm://Broker-three#18166
2016-03-28 11:43:18,414 | INFO  | Network connection between vm://Broker-three#18166 and tcp://localhost/127.0.0.1:61618@53872 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53872, localBroker= vm://Broker-three#18166
2016-03-28 11:43:18,416 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-613
2016-03-28 11:43:23,461 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:43:23,463 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18172:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53874, localBroker= vm://Broker-three#18168
2016-03-28 11:43:23,463 | INFO  | Network connection between vm://Broker-three#18168 and tcp://localhost/127.0.0.1:61618@53874 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53874, localBroker= vm://Broker-three#18168
2016-03-28 11:43:23,465 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-613
2016-03-28 11:43:28,508 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:43:28,510 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18174:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53876, localBroker= vm://Broker-three#18170
2016-03-28 11:43:28,510 | INFO  | Network connection between vm://Broker-three#18170 and tcp://localhost/127.0.0.1:61618@53876 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53876, localBroker= vm://Broker-three#18170
2016-03-28 11:43:28,513 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-612
2016-03-28 11:43:33,551 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:43:33,555 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18176:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53878, localBroker= vm://Broker-three#18172
2016-03-28 11:43:33,555 | INFO  | Network connection between vm://Broker-three#18172 and tcp://localhost/127.0.0.1:61618@53878 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53878, localBroker= vm://Broker-three#18172
2016-03-28 11:43:33,557 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-605
2016-03-28 11:43:38,595 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:43:38,598 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18178:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53880, localBroker= vm://Broker-three#18174
2016-03-28 11:43:38,598 | INFO  | Network connection between vm://Broker-three#18174 and tcp://localhost/127.0.0.1:61618@53880 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53880, localBroker= vm://Broker-three#18174
2016-03-28 11:43:38,600 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-613
2016-03-28 11:43:43,641 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:43:43,643 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18180:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53883, localBroker= vm://Broker-three#18176
2016-03-28 11:43:43,644 | INFO  | Network connection between vm://Broker-three#18176 and tcp://localhost/127.0.0.1:61618@53883 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53883, localBroker= vm://Broker-three#18176
2016-03-28 11:43:43,645 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-612
2016-03-28 11:43:48,685 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:43:48,689 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18182:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53885, localBroker= vm://Broker-three#18178
2016-03-28 11:43:48,689 | INFO  | Network connection between vm://Broker-three#18178 and tcp://localhost/127.0.0.1:61618@53885 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53885, localBroker= vm://Broker-three#18178
2016-03-28 11:43:48,691 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-613
2016-03-28 11:43:53,731 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:43:53,734 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18184:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53887, localBroker= vm://Broker-three#18180
2016-03-28 11:43:53,734 | INFO  | Network connection between vm://Broker-three#18180 and tcp://localhost/127.0.0.1:61618@53887 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53887, localBroker= vm://Broker-three#18180
2016-03-28 11:43:53,735 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-612
2016-03-28 11:43:58,778 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:43:58,780 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18186:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53890, localBroker= vm://Broker-three#18182
2016-03-28 11:43:58,781 | INFO  | Network connection between vm://Broker-three#18182 and tcp://localhost/127.0.0.1:61618@53890 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53890, localBroker= vm://Broker-three#18182
2016-03-28 11:43:58,782 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-612
2016-03-28 11:44:03,825 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:44:03,830 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18188:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53893, localBroker= vm://Broker-three#18184
2016-03-28 11:44:03,830 | INFO  | Network connection between vm://Broker-three#18184 and tcp://localhost/127.0.0.1:61618@53893 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53893, localBroker= vm://Broker-three#18184
2016-03-28 11:44:03,832 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-605
2016-03-28 11:44:08,873 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:44:08,875 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18190:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53897, localBroker= vm://Broker-three#18186
2016-03-28 11:44:08,875 | INFO  | Network connection between vm://Broker-three#18186 and tcp://localhost/127.0.0.1:61618@53897 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53897, localBroker= vm://Broker-three#18186
2016-03-28 11:44:08,877 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-613
2016-03-28 11:44:13,915 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:44:13,917 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18192:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53906, localBroker= vm://Broker-three#18188
2016-03-28 11:44:13,917 | INFO  | Network connection between vm://Broker-three#18188 and tcp://localhost/127.0.0.1:61618@53906 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53906, localBroker= vm://Broker-three#18188
2016-03-28 11:44:13,919 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-612
2016-03-28 11:44:18,954 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:44:18,957 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18194:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53911, localBroker= vm://Broker-three#18190
2016-03-28 11:44:18,957 | INFO  | Network connection between vm://Broker-three#18190 and tcp://localhost/127.0.0.1:61618@53911 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53911, localBroker= vm://Broker-three#18190
2016-03-28 11:44:18,960 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-613
2016-03-28 11:44:24,003 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:44:24,005 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18196:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53914, localBroker= vm://Broker-three#18192
2016-03-28 11:44:24,005 | INFO  | Network connection between vm://Broker-three#18192 and tcp://localhost/127.0.0.1:61618@53914 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53914, localBroker= vm://Broker-three#18192
2016-03-28 11:44:24,007 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-605
2016-03-28 11:44:29,048 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:44:29,053 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18198:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53916, localBroker= vm://Broker-three#18194
2016-03-28 11:44:29,054 | INFO  | Network connection between vm://Broker-three#18194 and tcp://localhost/127.0.0.1:61618@53916 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53916, localBroker= vm://Broker-three#18194
2016-03-28 11:44:29,057 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-605
2016-03-28 11:44:34,093 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:44:34,097 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18200:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53918, localBroker= vm://Broker-three#18196
2016-03-28 11:44:34,098 | INFO  | Network connection between vm://Broker-three#18196 and tcp://localhost/127.0.0.1:61618@53918 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53918, localBroker= vm://Broker-three#18196
2016-03-28 11:44:34,100 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-613
2016-03-28 11:44:39,137 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:44:39,139 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18202:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53920, localBroker= vm://Broker-three#18198
2016-03-28 11:44:39,139 | INFO  | Network connection between vm://Broker-three#18198 and tcp://localhost/127.0.0.1:61618@53920 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53920, localBroker= vm://Broker-three#18198
2016-03-28 11:44:39,141 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-612
2016-03-28 11:44:44,180 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:44:44,182 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18204:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53922, localBroker= vm://Broker-three#18200
2016-03-28 11:44:44,183 | INFO  | Network connection between vm://Broker-three#18200 and tcp://localhost/127.0.0.1:61618@53922 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53922, localBroker= vm://Broker-three#18200
2016-03-28 11:44:44,184 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-605
2016-03-28 11:44:49,227 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:44:49,230 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18206:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53924, localBroker= vm://Broker-three#18202
2016-03-28 11:44:49,230 | INFO  | Network connection between vm://Broker-three#18202 and tcp://localhost/127.0.0.1:61618@53924 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53924, localBroker= vm://Broker-three#18202
2016-03-28 11:44:49,232 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-613
2016-03-28 11:44:54,271 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:44:54,273 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18208:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53928, localBroker= vm://Broker-three#18204
2016-03-28 11:44:54,273 | INFO  | Network connection between vm://Broker-three#18204 and tcp://localhost/127.0.0.1:61618@53928 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53928, localBroker= vm://Broker-three#18204
2016-03-28 11:44:54,275 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-612
2016-03-28 11:44:59,318 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:44:59,320 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18210:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53930, localBroker= vm://Broker-three#18206
2016-03-28 11:44:59,320 | INFO  | Network connection between vm://Broker-three#18206 and tcp://localhost/127.0.0.1:61618@53930 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53930, localBroker= vm://Broker-three#18206
2016-03-28 11:44:59,321 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-605
2016-03-28 11:45:04,364 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:45:04,369 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18212:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53933, localBroker= vm://Broker-three#18208
2016-03-28 11:45:04,370 | INFO  | Network connection between vm://Broker-three#18208 and tcp://localhost/127.0.0.1:61618@53933 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53933, localBroker= vm://Broker-three#18208
2016-03-28 11:45:04,372 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-612
2016-03-28 11:45:09,404 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:45:09,407 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18214:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53935, localBroker= vm://Broker-three#18210
2016-03-28 11:45:09,407 | INFO  | Network connection between vm://Broker-three#18210 and tcp://localhost/127.0.0.1:61618@53935 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53935, localBroker= vm://Broker-three#18210
2016-03-28 11:45:09,409 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-613
2016-03-28 11:45:14,447 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:45:14,449 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18216:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53937, localBroker= vm://Broker-three#18212
2016-03-28 11:45:14,449 | INFO  | Network connection between vm://Broker-three#18212 and tcp://localhost/127.0.0.1:61618@53937 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53937, localBroker= vm://Broker-three#18212
2016-03-28 11:45:14,451 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-605
2016-03-28 11:45:19,492 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:45:19,495 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18218:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53939, localBroker= vm://Broker-three#18214
2016-03-28 11:45:19,495 | INFO  | Network connection between vm://Broker-three#18214 and tcp://localhost/127.0.0.1:61618@53939 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53939, localBroker= vm://Broker-three#18214
2016-03-28 11:45:19,497 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-612
2016-03-28 11:45:24,534 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:45:24,538 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18220:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53941, localBroker= vm://Broker-three#18216
2016-03-28 11:45:24,538 | INFO  | Network connection between vm://Broker-three#18216 and tcp://localhost/127.0.0.1:61618@53941 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53941, localBroker= vm://Broker-three#18216
2016-03-28 11:45:24,540 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-613
2016-03-28 11:45:29,578 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:45:29,581 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18222:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53943, localBroker= vm://Broker-three#18218
2016-03-28 11:45:29,581 | INFO  | Network connection between vm://Broker-three#18218 and tcp://localhost/127.0.0.1:61618@53943 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53943, localBroker= vm://Broker-three#18218
2016-03-28 11:45:29,582 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-605
2016-03-28 11:45:34,623 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:45:34,628 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18224:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53945, localBroker= vm://Broker-three#18220
2016-03-28 11:45:34,628 | INFO  | Network connection between vm://Broker-three#18220 and tcp://localhost/127.0.0.1:61618@53945 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53945, localBroker= vm://Broker-three#18220
2016-03-28 11:45:34,630 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-613
2016-03-28 11:45:39,666 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:45:39,668 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18226:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53948, localBroker= vm://Broker-three#18222
2016-03-28 11:45:39,669 | INFO  | Network connection between vm://Broker-three#18222 and tcp://localhost/127.0.0.1:61618@53948 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53948, localBroker= vm://Broker-three#18222
2016-03-28 11:45:39,670 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-612
2016-03-28 11:45:44,713 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:45:44,716 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18228:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53950, localBroker= vm://Broker-three#18224
2016-03-28 11:45:44,716 | INFO  | Network connection between vm://Broker-three#18224 and tcp://localhost/127.0.0.1:61618@53950 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53950, localBroker= vm://Broker-three#18224
2016-03-28 11:45:44,718 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-605
2016-03-28 11:45:49,760 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:45:49,763 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18230:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53960, localBroker= vm://Broker-three#18226
2016-03-28 11:45:49,763 | INFO  | Network connection between vm://Broker-three#18226 and tcp://localhost/127.0.0.1:61618@53960 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53960, localBroker= vm://Broker-three#18226
2016-03-28 11:45:49,765 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-613
2016-03-28 11:45:54,808 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:45:54,811 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18232:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53967, localBroker= vm://Broker-three#18228
2016-03-28 11:45:54,811 | INFO  | Network connection between vm://Broker-three#18228 and tcp://localhost/127.0.0.1:61618@53967 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53967, localBroker= vm://Broker-three#18228
2016-03-28 11:45:54,813 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-613
2016-03-28 11:45:59,850 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:45:59,853 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18234:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53971, localBroker= vm://Broker-three#18230
2016-03-28 11:45:59,853 | INFO  | Network connection between vm://Broker-three#18230 and tcp://localhost/127.0.0.1:61618@53971 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53971, localBroker= vm://Broker-three#18230
2016-03-28 11:45:59,854 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-605
2016-03-28 11:46:04,893 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:46:04,898 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18236:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53976, localBroker= vm://Broker-three#18232
2016-03-28 11:46:04,898 | INFO  | Network connection between vm://Broker-three#18232 and tcp://localhost/127.0.0.1:61618@53976 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53976, localBroker= vm://Broker-three#18232
2016-03-28 11:46:04,900 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-612
2016-03-28 11:46:09,940 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:46:09,943 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18238:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53978, localBroker= vm://Broker-three#18234
2016-03-28 11:46:09,943 | INFO  | Network connection between vm://Broker-three#18234 and tcp://localhost/127.0.0.1:61618@53978 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53978, localBroker= vm://Broker-three#18234
2016-03-28 11:46:09,945 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-613
2016-03-28 11:46:14,983 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:46:14,985 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18240:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53980, localBroker= vm://Broker-three#18236
2016-03-28 11:46:14,985 | INFO  | Network connection between vm://Broker-three#18236 and tcp://localhost/127.0.0.1:61618@53980 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53980, localBroker= vm://Broker-three#18236
2016-03-28 11:46:14,987 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-605
2016-03-28 11:46:20,027 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:46:20,030 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18242:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53982, localBroker= vm://Broker-three#18238
2016-03-28 11:46:20,030 | INFO  | Network connection between vm://Broker-three#18238 and tcp://localhost/127.0.0.1:61618@53982 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53982, localBroker= vm://Broker-three#18238
2016-03-28 11:46:20,032 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-612
2016-03-28 11:46:25,072 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:46:25,078 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18244:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53984, localBroker= vm://Broker-three#18240
2016-03-28 11:46:25,078 | INFO  | Network connection between vm://Broker-three#18240 and tcp://localhost/127.0.0.1:61618@53984 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53984, localBroker= vm://Broker-three#18240
2016-03-28 11:46:25,080 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-612
2016-03-28 11:46:30,116 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:46:30,119 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18246:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53986, localBroker= vm://Broker-three#18242
2016-03-28 11:46:30,119 | INFO  | Network connection between vm://Broker-three#18242 and tcp://localhost/127.0.0.1:61618@53986 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53986, localBroker= vm://Broker-three#18242
2016-03-28 11:46:30,126 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-613
2016-03-28 11:46:35,161 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:46:35,165 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18248:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53988, localBroker= vm://Broker-three#18244
2016-03-28 11:46:35,165 | INFO  | Network connection between vm://Broker-three#18244 and tcp://localhost/127.0.0.1:61618@53988 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53988, localBroker= vm://Broker-three#18244
2016-03-28 11:46:35,166 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-605
2016-03-28 11:46:40,206 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:46:40,212 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18250:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53990, localBroker= vm://Broker-three#18246
2016-03-28 11:46:40,212 | INFO  | Network connection between vm://Broker-three#18246 and tcp://localhost/127.0.0.1:61618@53990 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53990, localBroker= vm://Broker-three#18246
2016-03-28 11:46:40,216 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-605
2016-03-28 11:46:45,251 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:46:45,255 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18252:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53992, localBroker= vm://Broker-three#18248
2016-03-28 11:46:45,255 | INFO  | Network connection between vm://Broker-three#18248 and tcp://localhost/127.0.0.1:61618@53992 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53992, localBroker= vm://Broker-three#18248
2016-03-28 11:46:45,258 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-613
2016-03-28 11:46:50,296 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:46:50,300 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18254:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53994, localBroker= vm://Broker-three#18250
2016-03-28 11:46:50,300 | INFO  | Network connection between vm://Broker-three#18250 and tcp://localhost/127.0.0.1:61618@53994 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@53994, localBroker= vm://Broker-three#18250
2016-03-28 11:46:50,301 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-612
2016-03-28 11:46:55,344 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:46:55,347 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18256:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@54004, localBroker= vm://Broker-three#18252
2016-03-28 11:46:55,347 | INFO  | Network connection between vm://Broker-three#18252 and tcp://localhost/127.0.0.1:61618@54004 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@54004, localBroker= vm://Broker-three#18252
2016-03-28 11:46:55,349 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-605
2016-03-28 11:47:00,393 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:47:00,396 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18258:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@54006, localBroker= vm://Broker-three#18254
2016-03-28 11:47:00,396 | INFO  | Network connection between vm://Broker-three#18254 and tcp://localhost/127.0.0.1:61618@54006 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@54006, localBroker= vm://Broker-three#18254
2016-03-28 11:47:00,398 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-613
2016-03-28 11:47:05,436 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:47:05,440 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18260:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@54009, localBroker= vm://Broker-three#18256
2016-03-28 11:47:05,440 | INFO  | Network connection between vm://Broker-three#18256 and tcp://localhost/127.0.0.1:61618@54009 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@54009, localBroker= vm://Broker-three#18256
2016-03-28 11:47:05,442 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-612
2016-03-28 11:47:10,484 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:47:10,487 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18262:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@54011, localBroker= vm://Broker-three#18258
2016-03-28 11:47:10,487 | INFO  | Network connection between vm://Broker-three#18258 and tcp://localhost/127.0.0.1:61618@54011 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@54011, localBroker= vm://Broker-three#18258
2016-03-28 11:47:10,489 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-605
2016-03-28 11:47:15,521 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:47:15,524 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18264:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@54013, localBroker= vm://Broker-three#18260
2016-03-28 11:47:15,524 | INFO  | Network connection between vm://Broker-three#18260 and tcp://localhost/127.0.0.1:61618@54013 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@54013, localBroker= vm://Broker-three#18260
2016-03-28 11:47:15,528 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-613
2016-03-28 11:47:20,568 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:47:20,571 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18266:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@54016, localBroker= vm://Broker-three#18262
2016-03-28 11:47:20,571 | INFO  | Network connection between vm://Broker-three#18262 and tcp://localhost/127.0.0.1:61618@54016 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@54016, localBroker= vm://Broker-three#18262
2016-03-28 11:47:20,572 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-612
2016-03-28 11:47:25,614 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:47:25,616 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18268:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@54018, localBroker= vm://Broker-three#18264
2016-03-28 11:47:25,616 | INFO  | Network connection between vm://Broker-three#18264 and tcp://localhost/127.0.0.1:61618@54018 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@54018, localBroker= vm://Broker-three#18264
2016-03-28 11:47:25,618 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-605
2016-03-28 11:47:30,658 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:47:30,660 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18270:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@54020, localBroker= vm://Broker-three#18266
2016-03-28 11:47:30,660 | INFO  | Network connection between vm://Broker-three#18266 and tcp://localhost/127.0.0.1:61618@54020 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@54020, localBroker= vm://Broker-three#18266
2016-03-28 11:47:30,662 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-613
2016-03-28 11:47:35,702 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:47:35,707 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18272:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@54023, localBroker= vm://Broker-three#18268
2016-03-28 11:47:35,707 | INFO  | Network connection between vm://Broker-three#18268 and tcp://localhost/127.0.0.1:61618@54023 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@54023, localBroker= vm://Broker-three#18268
2016-03-28 11:47:35,709 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-612
2016-03-28 11:47:40,744 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:47:40,747 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18274:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@54027, localBroker= vm://Broker-three#18270
2016-03-28 11:47:40,747 | INFO  | Network connection between vm://Broker-three#18270 and tcp://localhost/127.0.0.1:61618@54027 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@54027, localBroker= vm://Broker-three#18270
2016-03-28 11:47:40,748 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-605
2016-03-28 11:47:45,783 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:47:45,786 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18276:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@54040, localBroker= vm://Broker-three#18272
2016-03-28 11:47:45,786 | INFO  | Network connection between vm://Broker-three#18272 and tcp://localhost/127.0.0.1:61618@54040 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@54040, localBroker= vm://Broker-three#18272
2016-03-28 11:47:45,788 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-612
2016-03-28 11:47:50,827 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:47:50,830 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18278:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@54052, localBroker= vm://Broker-three#18274
2016-03-28 11:47:50,830 | INFO  | Network connection between vm://Broker-three#18274 and tcp://localhost/127.0.0.1:61618@54052 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@54052, localBroker= vm://Broker-three#18274
2016-03-28 11:47:50,832 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-605
2016-03-28 11:47:55,874 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:47:55,877 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18280:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@54057, localBroker= vm://Broker-three#18276
2016-03-28 11:47:55,877 | INFO  | Network connection between vm://Broker-three#18276 and tcp://localhost/127.0.0.1:61618@54057 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@54057, localBroker= vm://Broker-three#18276
2016-03-28 11:47:55,879 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-605
2016-03-28 11:48:00,923 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:48:00,926 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18282:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@54062, localBroker= vm://Broker-three#18278
2016-03-28 11:48:00,927 | INFO  | Network connection between vm://Broker-three#18278 and tcp://localhost/127.0.0.1:61618@54062 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@54062, localBroker= vm://Broker-three#18278
2016-03-28 11:48:00,934 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-605
2016-03-28 11:48:05,967 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:48:05,971 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18284:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@54064, localBroker= vm://Broker-three#18280
2016-03-28 11:48:05,971 | INFO  | Network connection between vm://Broker-three#18280 and tcp://localhost/127.0.0.1:61618@54064 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@54064, localBroker= vm://Broker-three#18280
2016-03-28 11:48:05,973 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-613
2016-03-28 11:48:11,010 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:48:11,013 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18286:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@54071, localBroker= vm://Broker-three#18282
2016-03-28 11:48:11,013 | INFO  | Network connection between vm://Broker-three#18282 and tcp://localhost/127.0.0.1:61618@54071 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@54071, localBroker= vm://Broker-three#18282
2016-03-28 11:48:11,015 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-605
2016-03-28 11:48:16,056 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:48:16,058 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18288:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@54074, localBroker= vm://Broker-three#18284
2016-03-28 11:48:16,058 | INFO  | Network connection between vm://Broker-three#18284 and tcp://localhost/127.0.0.1:61618@54074 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@54074, localBroker= vm://Broker-three#18284
2016-03-28 11:48:16,060 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-612
2016-03-28 11:48:21,101 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:48:21,104 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18290:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@54076, localBroker= vm://Broker-three#18286
2016-03-28 11:48:21,104 | INFO  | Network connection between vm://Broker-three#18286 and tcp://localhost/127.0.0.1:61618@54076 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@54076, localBroker= vm://Broker-three#18286
2016-03-28 11:48:21,106 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-613
2016-03-28 11:48:26,145 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:48:26,148 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18292:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@54078, localBroker= vm://Broker-three#18288
2016-03-28 11:48:26,148 | INFO  | Network connection between vm://Broker-three#18288 and tcp://localhost/127.0.0.1:61618@54078 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@54078, localBroker= vm://Broker-three#18288
2016-03-28 11:48:26,150 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-605
2016-03-28 11:48:31,186 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:48:31,190 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18294:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@54081, localBroker= vm://Broker-three#18290
2016-03-28 11:48:31,190 | INFO  | Network connection between vm://Broker-three#18290 and tcp://localhost/127.0.0.1:61618@54081 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@54081, localBroker= vm://Broker-three#18290
2016-03-28 11:48:31,192 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-612
2016-03-28 11:48:36,231 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:48:36,236 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18296:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@54083, localBroker= vm://Broker-three#18292
2016-03-28 11:48:36,236 | INFO  | Network connection between vm://Broker-three#18292 and tcp://localhost/127.0.0.1:61618@54083 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@54083, localBroker= vm://Broker-three#18292
2016-03-28 11:48:36,238 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-613
2016-03-28 11:48:41,275 | INFO  | Establishing network connection from vm://Broker-three?async=false to tcp://localhost:61618 | org.apache.activemq.network.DiscoveryNetworkConnector | Notifier-MulticastDiscoveryAgent-listener:DiscoveryNetworkConnector:NC:BrokerService[Broker-three]
2016-03-28 11:48:41,278 | WARN  | Failed to add Connection Broker-three->Broker-two-62079-1458672414839-18298:1 due to javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.broker.TransportConnection | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@54085, localBroker= vm://Broker-three#18294
2016-03-28 11:48:41,278 | INFO  | Network connection between vm://Broker-three#18294 and tcp://localhost/127.0.0.1:61618@54085 shutdown due to a local error: javax.jms.InvalidClientIDException: Broker: Broker-three - Client: NC_Broker-two_inbound_Broker-three already connected from vm://Broker-three#4 | org.apache.activemq.network.DemandForwardingBridgeSupport | triggerStartAsyncNetworkBridgeCreation: remoteBroker=tcp://localhost/127.0.0.1:61618@54085, localBroker= vm://Broker-three#18294
2016-03-28 11:48:41,280 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-612
2016-03-28 11:48:44,201 | INFO  | Apache ActiveMQ 5.13.2 (Broker-three, ID:Jeferson-Machados-MacBook-Pro.local-62079-1458672414839-0:1) is shutting down | org.apache.activemq.broker.BrokerService | Thread-16
2016-03-28 11:48:44,209 | INFO  | Network Connector DiscoveryNetworkConnector:NC:BrokerService[Broker-three] stopped | org.apache.activemq.network.NetworkConnector | Thread-16
2016-03-28 11:48:44,213 | INFO  | socketQueue interrupted - stopping | org.apache.activemq.transport.tcp.TcpTransportServer | ActiveMQ Transport Server Thread Handler: tcp://localhost:61619
2016-03-28 11:48:44,214 | ERROR | Could not accept connection : java.lang.InterruptedException | org.apache.activemq.broker.TransportConnector | ActiveMQ Transport Server Thread Handler: tcp://localhost:61619
2016-03-28 11:48:44,217 | INFO  | Connector tcp://localhost:61619 stopped | org.apache.activemq.broker.TransportConnector | Thread-16
2016-03-28 11:48:44,218 | INFO  | Broker-three Shutting down NC | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-605
2016-03-28 11:48:44,221 | INFO  | Broker-three bridge to Broker-two stopped | org.apache.activemq.network.DemandForwardingBridgeSupport | ActiveMQ BrokerService[Broker-three] Task-605
2016-03-28 11:48:44,222 | INFO  | Connector vm://Broker-three stopped | org.apache.activemq.broker.TransportConnector | Thread-16
2016-03-28 11:48:44,279 | INFO  | PListStore:[/Volumes/HD/Documents/Development/github/sandbox/Arch/ActiveMQ/activemq-cluster/apache-activemq-5.13.2-three/activemq-data/Broker-three/tmp_storage] stopped | org.apache.activemq.store.kahadb.plist.PListStoreImpl | Thread-16
2016-03-28 11:48:44,317 | INFO  | Apache ActiveMQ 5.13.2 (Broker-three, ID:Jeferson-Machados-MacBook-Pro.local-62079-1458672414839-0:1) uptime 5 days 20 hours | org.apache.activemq.broker.BrokerService | Thread-16
2016-03-28 11:48:44,317 | INFO  | Apache ActiveMQ 5.13.2 (Broker-three, ID:Jeferson-Machados-MacBook-Pro.local-62079-1458672414839-0:1) is shutdown | org.apache.activemq.broker.BrokerService | Thread-16
